### ISSUE TITLE
State not syncing across components

### ISSUE THREAD

**Issue by franciscop** [nas5w/use-local-storage#28] opened 2022-11-06 12:32 UTC
**Describe the bug**
When you modify localStorage from another tab, the state updates correctly. However when you modify state from another component, an update is not triggered. This library lacks a pub/sub to make it possible.

**To Reproduce**
Click one button here. The other should update as well (but it doesn't):
https://codesandbox.io/s/xenodochial-herschel-xptrbl?file=/src/App.js

**Expected behavior**
The state syncs for the same component (works), across components (bug) and across tabs (works). Only across components is broken now, which is very odd.

**Screenshots**
<img width="398" alt="image" src="https://user-images.githubusercontent.com/2801252/200170942-44857eb5-88a0-42a5-8c30-2eeb620c1b58.png">

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**
I'd recommend a simple pub/sub system across keys and using the provided callbacks.

**Comment by nas5w** [comment] 2022-11-06 17:03
@franciscop thank you for opening this issue!

This to me is expected behavior _right now_: syncing state is neither a function of a normal `useState` hook nor local storage.

So I guess the question is whether we should add some kind of functionality to sync state across components. For me, the intuitive way to do this would just be to use the `useLocalStorage` hook in a React context provider or some other existing state-sharing mechanism.

That being said, it's worth considering offering a mechanism to sync state using this hook, but I'd like to take a bit of time to discuss here the pros and cons of doing so.

**Comment by franciscop** [comment] 2022-11-06 18:42
Agreed if they were independent, but the problem is that there is a single underlying data store, so if two components go out of sync then which is the underlying saved value? It's very fragile in that instance. Now the components are a bit too much IMHO "useState()"-like with a localStorage backup, while IMHO how most people would think about them is a bit more like "localStorage"-first with useful hooks like useState, if that makes sense.

Since there's a single underlying data store, I believe it's better to consider this more akin to Redux and have a global store that keeps everything in sync than as a purely-local `useState()`.

Note that this has some implications, like having a "set undefined to delete" but "use default value if nothing is there" is a bit confusing as well if we have a single data store, or having a default per-component that overwrites the global one (since there could be a race condition there as well if two different components have different defaults).

**Comment by nas5w** [comment] 2022-11-15 22:08
@jrabek thanks! Ok, sounds like this needs to go in. I believe it should be pretty doable With storage events. Please let me know if either of you wants to attempt adding it to the package. If not, I will carve out time to do it. 

Thanks again!

**Comment by franciscop** [comment] 2022-11-16 11:47
Unfortunately storage events only work from different tabs, not within the same one:

> The storage event of the [Window](https://developer.mozilla.org/en-US/docs/Web/API/Window) interface fires when a storage area (localStorage) has been modified in the context of another document.
> Note: This won't work on the same page that is making the changes — it is really a way for other pages on the domain using the storage to sync any changes that are made. Pages on other domains can't access the same storage objects. - [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event)

BTW I have since created my own full `use-storage` that fixed the 2 issues I opened and is more clear about overwriting vs not overwriting the storage when undefined (since using default args, it's clear that it won't be overwriting anything). But the API is different enough that I haven't made it into a PR here:

https://github.com/franciscop/use-storage

**Comment by jrabek** [comment] 2022-11-16 12:33
Oh nice! Will check it out.  I ended up using https://github.com/rehooks/local-storage since it fit the needs I had for what I am working on.  I haven't compared its implementation with your use-storage yet.

**Comment by macrozone** [comment] 2022-11-23 15:53
thx @franciscop ! 

I came here because the `useLocalStorage` hook from `react-use` has the same problem https://github.com/streamich/react-use/issues/1831


I noticed that many implementations of this hook have the same problem, because it was popularized on https://usehooks.com/useLocalStorage/

As @franciscop noticed, this is wrong as it leads to an inconsistency. the localStorage is the one source-of-truth and the hook always has to return that exact value.

**Comment by franciscop** [comment] 2022-11-23 18:46
Wait why is typescript a reason not to use a repo? Because TS helps avoiding bugs? Wouldn't that be very ironic in this context? 😎

**Comment by macrozone** [comment] 2022-11-23 20:36
> Wait why is typescript a reason not to use a repo? Because TS helps avoiding bugs? Wouldn't that be very ironic in this context? 😎

avoiding bugs like
```
const [value, setVale] = useState<string[]>([])

setValue(["hello", "world"]) 
setValue("Bug!") // shows error with proper typings
```

should be reason enough

**Comment by franciscop** [comment] 2022-11-24 00:06
Sure, you can just add types to your project if you prefer to use TS without making libraries to also move to TS:

https://medium.com/@steveruiz/using-a-javascript-library-without-type-declarations-in-a-typescript-project-3643490015f3#3673

**Comment by macrozone** [comment] 2022-11-24 10:32
> Sure, you can just add types to your project if you prefer to use TS without making libraries to also move to TS:
> 
> https://medium.com/@steveruiz/using-a-javascript-library-without-type-declarations-in-a-typescript-project-3643490015f3#3673

I know this ;-) Its just not a good practise, because you won't spot breaking changes. Its a pitfall that I would highly recommend to avoid. 

I am thankful to everyone who contributes to open source and releases packages! But I also recommend to be cautious in what you select to use. Packages that are not in typescript (or at least have no official maintained type-definition) is one thing I would avoid. I just got burned by that.

I also think most code bases profit from typescript, it removes cognitive overhead if done right  and helps to avoid bugs.

**Comment by doganhekimoglu** [comment] 2023-04-08 23:28
> @franciscop thank you for opening this issue!
> 
> This to me is expected behavior _right now_: syncing state is neither a function of a normal `useState` hook nor local storage.
> 
> So I guess the question is whether we should add some kind of functionality to sync state across components. For me, the intuitive way to do this would just be to use the `useLocalStorage` hook in a React context provider or some other existing state-sharing mechanism.
> 
> That being said, it's worth considering offering a mechanism to sync state using this hook, but I'd like to take a bit of time to discuss here the pros and cons of doing so.

Hi @nas5w , I was thinking about creating a hook myself for localStorage but then I came across your project. Actually to overcome this problem you don't need anything like context provider. You can just dispatch a storage event manually like

![image](https://user-images.githubusercontent.com/39832865/230746439-5aa86501-c484-49df-b834-be1adb855ba1.png)

before or after you call `localStorage.setItem` in your code so the event listeners in the same document will get notified about this event as well and the state will be synced across the components on the same page. So, this way all the hook calls for the same storage key will be in sync whether it is across different tabs or different components.

I think this is the last important piece this hook is missing.

**Closed** 2023-04-24 00:23 UTC
